### ISSUE TITLE
Build instructions improvements

### ISSUE THREAD

**Issue by fharding1** [PhotonVision/photonvision-docs#7]
I just went through the build instructions. Some thoughts:

* It would be nice if there were OS-specific build prerequisites, e.g. an `apt` command for Ubuntu. Tabs would be perfect for this
* I think "In the photonvision-server directory (${PROJECT_DIR}/photon-server):" could be shortened to "In the `photon-server/` directory" and it would be less confusing to newbies. I don't think there's any reason to specify an envvar
* The gradlew build command should probably be `./gradlew` not `gradlew` (unless that doesn't work on Windows, then both should be listed with tabs). Otherwise a Linux user unfamiliar with gradle might think they have to install it or something
* The client app is missing the `vue-cli-service` dependency. I had to manually `npm install @vue/cli-service` in the client directory to get `gradlew` to build
* Why does `./gradlew run` seem to hang at "75% EXECUTING" while running? Is this a me-issue?

**Comment by vatanaksoytezer** [comment]
Hey, thanks for the issue. I think I can work on fixing the first 4 bullet points. 

1) At first i though of doing the tab thingy but had a weird extra space with tabs. I guess I will have to work that out. 
2) I can totally do that.
3) Will be fixed with tabs.
4) I will make sure to add this.
5) This one idk but probably @Bankst or @mcm001 have an answer for that.

Will send a PR in a day or two with fixes.

Thanks for the input!
